import { buildKinney } from "./kinney";
import { addDays, isoDay } from "./format";
import { defaultObjectives } from "./pgp";
import type { Anomaly, FdsNotice, PgpPlan, Profile, RpsSituation, Visit, Workspace } from "./types";
import { DEMO_WORKSPACE_ID } from "./workspace";

export const DEFAULT_PROFILE: Profile = {
  name: "Camille Dubois",
  title: "Conseiller en prévention",
  level: 2,
  organisation: "SIPP interne — Ateliers Van den Berg",
  kind: "entreprise",
  workspaceId: DEMO_WORKSPACE_ID,
};

const today = isoDay();
const lastWeek = addDays(today, -8);
const stamp = `${today}T08:15:00.000Z`;

export const SEED_WORKSPACES: Workspace[] = [
  {
    id: DEMO_WORKSPACE_ID,
    kind: "entreprise",
    name: "Ateliers Van den Berg SPRL",
    code: "DEMO01",
    createdAt: stamp,
  },
];

export const SEED_VISITS: Visit[] = [
  {
    id: "visit-vdb",
    name: "Atelier 3 Charleroi",
    company: "Ateliers Van den Berg SPRL",
    site: "Charleroi — Atelier 3",
    interlocutor: "Marc Lemoine, chef d'atelier",
    date: today,
    status: "en_cours",
    coverPhoto: "/seed/atelier.jpg",
    notes: "Visite de conformité trimestrielle. Focus électricité et issues.",
    workspaceId: DEMO_WORKSPACE_ID,
    geo: {
      lat: 50.41082,
      lng: 4.44458,
      address: "Rue de Montigny 42, 6000 Charleroi",
      capturedAt: stamp,
    },
    place: {
      street: "Rue de Montigny",
      number: "42",
      postcode: "6000",
      city: "Charleroi",
      country: "Belgique",
      building: "Ateliers Van den Berg",
      house: "",
      floor: "RDC",
      unit: "",
      room: "Atelier 3",
      extra: "Colonne nord",
      lat: 50.41082,
      lng: 4.44458,
      label: "Rue de Montigny 42, 6000 Charleroi",
      verified: true,
      source: "search",
    },
  },
  {
    id: "visit-lambert",
    name: "Garage Lambert",
    company: "Garage Lambert",
    site: "Liège — Atelier carrosserie",
    interlocutor: "Sophie Lambert, gérante",
    date: lastWeek,
    status: "terminee",
    coverPhoto: "/seed/solvant.jpg",
    notes: "Visite clôturée. Actions chimiques et EPI transmises.",
    workspaceId: DEMO_WORKSPACE_ID,
    geo: {
      lat: 50.63256,
      lng: 5.57966,
      address: "Rue de la Carrosserie 8, 4020 Liège",
      capturedAt: new Date(`${lastWeek}T09:00:00`).toISOString(),
    },
    place: {
      street: "Rue de la Carrosserie",
      number: "8",
      postcode: "4020",
      city: "Liège",
      country: "Belgique",
      building: "Garage Lambert",
      house: "",
      floor: "RDC",
      unit: "",
      room: "Atelier carrosserie",
      extra: "",
      lat: 50.63256,
      lng: 5.57966,
      label: "Rue de la Carrosserie 8, 4020 Liège",
      verified: true,
      source: "search",
    },
    signatures: [
      {
        role: "conseiller",
        name: "Camille Dubois",
        dataUrl: "",
        signedAt: new Date(`${lastWeek}T16:40:00`).toISOString(),
      },
      {
        role: "site",
        name: "Sophie Lambert",
        dataUrl: "",
        signedAt: new Date(`${lastWeek}T16:42:00`).toISOString(),
      },
    ],
  },
];

export const SEED_ANOMALIES: Anomaly[] = [
  {
    id: "ano-cable",
    author: { name: DEFAULT_PROFILE.name, title: DEFAULT_PROFILE.title, level: DEFAULT_PROFILE.level },
    visitId: "visit-vdb",
    workspaceId: DEMO_WORKSPACE_ID,
    photo: "/seed/cable.jpg",
    title: "Câble dénudé — prise atelier 3",
    location: "Atelier 3, colonne nord",
    description:
      "Conducteur cuivre apparent sur boîte de dérivation endommagée. Personnel au contact quotidien. Risque d'électrocution.",
    transcription: "Prise atelier 3, risque d'électrocution, urgence haute.",
    theme: "electricite",
    urgency: "haute",
    kinney: buildKinney(6, 6, 15),
    legalRef: "Code du bien-être au travail — Livre III (Installations électriques)",
    status: "validee",
    correctiveAction:
      "Consigner immédiatement, isoler le conducteur, intervention électricien BA4/BA5, rétablir le protecteur et tester.",
    assignedTo: "Marc Lemoine",
    dueDate: addDays(today, 2),
    createdAt: stamp,
    capturedAt: stamp,
    geo: {
      lat: 50.41082,
      lng: 4.44458,
      address: "Atelier 3, Rue de Montigny 42, 6000 Charleroi",
      capturedAt: stamp,
    },
    voice: {
      danger: "Conducteur cuivre apparent, risque d'électrocution au poste.",
      measure: "Consigner, isoler, intervention BA4/BA5.",
      zone: "Atelier 3, colonne nord — prise murale",
    },
    kinneyWhy: {
      Pwhy: "P = 6 — contact possible : la prise est utilisée plusieurs fois par poste.",
      Ewhy: "E = 6 — exposition quotidienne de l'équipe atelier 3.",
      Gwhy: "G = 15 — électrocution / brûlure grave, invalidité possible.",
      legal: "Code du bien-être — Livre III, installations électriques. Suggestion à valider.",
    },
  },
  {
    id: "ano-issue",
    author: { name: DEFAULT_PROFILE.name, title: DEFAULT_PROFILE.title, level: DEFAULT_PROFILE.level },
    visitId: "visit-vdb",
    workspaceId: DEMO_WORKSPACE_ID,
    photo: "/seed/issue.jpg",
    title: "Issue de secours obstruée",
    location: "Atelier 3, façade ouest",
    description:
      "Palettes et cartons stockés devant la porte de sortie de secours. Dégagement d'évacuation non garanti.",
    transcription: "Issue de secours bloquée par des palettes, atelier 3.",
    theme: "incendie",
    urgency: "critique",
    kinney: buildKinney(3, 6, 15),
    legalRef: "Code du bien-être au travail — Livre III (Lieux de travail / incendie)",
    status: "ouverte",
    correctiveAction:
      "Libérer le dégagement immédiatement, interdire le stockage, marquer au sol la zone de dégagement, briefing équipe.",
    assignedTo: "Marc Lemoine",
    dueDate: addDays(today, 1),
    createdAt: stamp,
  },
  {
    id: "ano-manutention",
    author: { name: DEFAULT_PROFILE.name, title: DEFAULT_PROFILE.title, level: DEFAULT_PROFILE.level },
    visitId: "visit-vdb",
    workspaceId: DEMO_WORKSPACE_ID,
    photo: "/seed/manutention.jpg",
    title: "Sacs 25 kg sans aide à la manutention",
    location: "Quai de réception",
    description:
      "Sacs de grenaille de 25 kg manutentionnés à la main, sans transpalette ni limitation de poids. Risque TMS.",
    transcription: "Manutention sacs 25 kilos au quai, pas d'aide mécanique.",
    theme: "ergonomie",
    urgency: "moyenne",
    kinney: buildKinney(6, 6, 7),
    legalRef: "Code du bien-être au travail — Livre VIII (Ergonomie et manutention)",
    status: "ouverte",
    correctiveAction:
      "Mettre un transpalette à disposition, fractionner les charges, former aux gestes et postures.",
    assignedTo: "Chef de quai",
    dueDate: addDays(today, 21),
    createdAt: stamp,
  },
  {
    id: "ano-solvant",
    author: { name: DEFAULT_PROFILE.name, title: DEFAULT_PROFILE.title, level: DEFAULT_PROFILE.level },
    visitId: "visit-lambert",
    workspaceId: DEMO_WORKSPACE_ID,
    photo: "/seed/solvant.jpg",
    title: "Fût de solvant sans extraction",
    location: "Cabine peinture",
    description:
      "Fût de dégraissant ouvert hors armoire ventilée. Vapeurs inflammables. FDS non affichée au poste.",
    theme: "chimie",
    urgency: "haute",
    kinney: buildKinney(6, 6, 15),
    legalRef: "Code du bien-être au travail — Livre VI (Agents chimiques)",
    status: "en_cours",
    correctiveAction:
      "Refermer et stocker en armoire de sécurité, installer l'aspiration au poste, afficher la notice simplifiée.",
    assignedTo: "Sophie Lambert",
    dueDate: addDays(lastWeek, 14),
    createdAt: new Date(`${lastWeek}T09:30:00`).toISOString(),
  },
  {
    id: "ano-epi",
    author: { name: DEFAULT_PROFILE.name, title: DEFAULT_PROFILE.title, level: DEFAULT_PROFILE.level },
    visitId: "visit-lambert",
    workspaceId: DEMO_WORKSPACE_ID,
    photo: "/seed/solvant.jpg",
    title: "Lunettes de protection absentes au poste peinture",
    location: "Cabine peinture",
    description:
      "Aucun EPI oculaire à disposition malgré les pictogrammes du produit. Risque de projections.",
    theme: "epi",
    urgency: "haute",
    kinney: buildKinney(6, 6, 7),
    legalRef: "Code du bien-être au travail — Livre IX (EPI)",
    status: "cloturee",
    correctiveAction: "Distributeur de lunettes installé. Contrôle de port hebdomadaire en place.",
    assignedTo: "Sophie Lambert",
    dueDate: addDays(lastWeek, 7),
    createdAt: new Date(`${lastWeek}T10:00:00`).toISOString(),
  },
];

export const SEED_FDS: FdsNotice[] = [
  {
    id: "fds-solvex",
    workspaceId: DEMO_WORKSPACE_ID,
    productName: "SOLVEX 300",
    manufacturer: "AtelierChim SPRL",
    photo: "/seed/solvex-label.jpg",
    pictograms: ["GHS02", "GHS05", "GHS08"],
    signalWord: "DANGER",
    hazards: [
      "H225 — Liquide et vapeurs très inflammables",
      "H314 — Provoque de graves brûlures de la peau et de graves lésions des yeux",
      "H373 — Risque d'effets graves pour les organes à la suite d'expositions répétées",
    ],
    ppe: ["Gants nitrile", "Lunettes étanches", "Tablier chimique", "Ventilation / masque A2"],
    firstAid:
      "Rincer à grande eau 15 min. Retirer les vêtements souillés. Appeler le 112 si projection oculaire.",
    notice: [
      "Produit inflammable et corrosif — interdiction de flamme et d'étincelle.",
      "Porter gants nitrile + lunettes avant toute ouverture du fût.",
      "Travailler uniquement sous aspiration ou à l'air libre.",
      "En cas de contact : rincer 15 minutes, prévenir le chef d'atelier.",
      "Refermer le contenant et ranger en armoire de sécurité après usage.",
    ],
    visitId: "visit-vdb",
    reality: {
      products: "SOLVEX 300 — dégraissage des pièces métalliques à l'atelier 3",
      hazards:
        "Liquide et vapeurs très inflammables, corrosif (brûlures), effets graves sur les organes en cas d'expositions répétées (H225, H314, H373).",
      exposed: "Opérateurs atelier 3 et intérimaires de nettoyage, environ 4 personnes",
      duration: "2 à 3 heures par poste, plusieurs fois par semaine",
      prevention:
        "FDS à jour, étiquette CLP visible, aspiration, gants nitrile, lunettes étanches, armoire de sécurité.",
      themes: ["fds", "etiquettes_clp", "ventilation", "epi", "protection_collective"],
    },
    createdAt: new Date(`${lastWeek}T11:00:00`).toISOString(),
  },
  {
    id: "fds-peinture",
    workspaceId: DEMO_WORKSPACE_ID,
    productName: "PEINTURE 2K CARROSSERIE",
    manufacturer: "Coatings Benelux",
    pictograms: ["GHS02", "GHS07", "GHS08"],
    signalWord: "DANGER",
    hazards: [
      "H226 — Liquide et vapeurs inflammables",
      "H317 — Peut provoquer une allergie cutanée",
      "H351 — Susceptible de provoquer le cancer",
    ],
    ppe: ["Gants nitrile", "Masque A2P3", "Combinaison", "Lunettes"],
    firstAid: "Air frais. Laver la peau au savon. Consulter si irritation persiste.",
    notice: [
      "Peinture 2K — durcisseur isocyanate, CMR suspecté.",
      "Pulvériser uniquement en cabine ventilée, masque A2P3 obligatoire.",
      "Gants et combinaison à usage unique, pas de contact cutané.",
      "Ne jamais mélanger hors des ratios indiqués sur la fiche.",
      "Déchets = déchets dangereux, fût étiqueté dédié.",
    ],
    reality: {
      products: "Peinture 2K carrosserie + durcisseur isocyanate",
      hazards: "Inflammable, allergie cutanée, CMR suspecté (H226, H317, H351).",
      prevention: "Cabine ventilée, masque A2P3, gants et combinaison à usage unique.",
      themes: ["fds", "etiquettes_clp", "ventilation", "epi"],
    },
    createdAt: new Date(`${lastWeek}T11:20:00`).toISOString(),
  },
];

export const SEED_PGP: PgpPlan = {
  company: "Ateliers Van den Berg SPRL",
  employer: "Jean Van den Berg",
  workers: 47,
  sipp: "Camille Dubois, conseiller interne",
  physician: "Dr. Aline Mertens — CESI",
  pgpStart: 2024,
  pgpEnd: 2028,
  paaYear: 2026,
  cpptDate: "2026-03-12",
  budget: 18500,
  status: "brouillon",
  notes:
    "PAA 2026 construit à partir des visites Charleroi et Liège. Priorité : électricité, issues, chimie cabine peinture.",
  objectives: defaultObjectives(),
  lines: [
    {
      id: "paa-cable",
      anomalyId: "ano-cable",
      title: "Câble dénudé — prise atelier 3",
      theme: "electricite",
      measure:
        "Consigner, isoler le conducteur, intervention BA4/BA5, rétablir le protecteur.",
      owner: "Marc Lemoine",
      dueDate: addDays(today, 2),
      quarter: "Q3",
      budget: 1800,
      included: true,
      status: "retenue",
      origin: "visite",
      level: 1,
    },
    {
      id: "paa-issue",
      anomalyId: "ano-issue",
      title: "Issue de secours obstruée",
      theme: "incendie",
      measure: "Libérer le dégagement, marquage au sol, briefing équipe.",
      owner: "Marc Lemoine",
      dueDate: addDays(today, 1),
      quarter: "Q3",
      budget: 400,
      included: true,
      status: "retenue",
      origin: "visite",
      level: 1,
    },
    {
      id: "paa-manutention",
      anomalyId: "ano-manutention",
      title: "Sacs 25 kg sans aide à la manutention",
      theme: "ergonomie",
      measure: "Transpalette au quai, fractionner les charges, formation gestes et postures.",
      owner: "Chef de quai",
      dueDate: addDays(today, 21),
      quarter: "Q3",
      budget: 3500,
      included: true,
      status: "retenue",
      origin: "visite",
      level: 2,
    },
    {
      id: "paa-solvant",
      anomalyId: "ano-solvant",
      title: "Fût de solvant sans extraction",
      theme: "chimie",
      measure: "Armoire de sécurité, aspiration au poste, notice simplifiée affichée.",
      owner: "Sophie Lambert",
      dueDate: addDays(lastWeek, 14),
      quarter: "Q3",
      budget: 2200,
      included: true,
      status: "retenue",
      origin: "visite",
      level: 2,
    },
    {
      id: "paa-epi",
      anomalyId: "ano-epi",
      title: "Lunettes de protection au poste peinture",
      theme: "epi",
      measure: "Distributeur de lunettes et contrôle de port hebdomadaire.",
      owner: "Sophie Lambert",
      dueDate: addDays(lastWeek, 7),
      quarter: "Q3",
      budget: 900,
      included: true,
      status: "realisee",
      origin: "visite",
      level: 3,
    },
    {
      id: "paa-ba4",
      title: "Formation BA4 / BA5 des référents électricité",
      theme: "electricite",
      measure: "Habiliter 4 personnes atelier 3. Recyclage des habilitations échues.",
      owner: "Camille Dubois",
      dueDate: "2026-04-30",
      quarter: "Q2",
      budget: 2400,
      included: true,
      status: "retenue",
      origin: "pgp",
      level: 2,
    },
    {
      id: "paa-evac",
      title: "Exercice d'évacuation annuel",
      theme: "incendie",
      measure: "Deux exercices (jour + équipe tardive), débriefing CPPT.",
      owner: "Marc Lemoine",
      dueDate: "2026-06-15",
      quarter: "Q2",
      budget: 800,
      included: true,
      status: "retenue",
      origin: "pgp",
      level: 2,
    },
    {
      id: "paa-rps",
      title: "Analyse des risques psychosociaux",
      theme: "psychosociaux",
      measure: "Analyses RPS collectives (situation, pas personnes) + restitution CPPT.",
      owner: "Camille Dubois",
      dueDate: "2026-11-30",
      quarter: "Q4",
      budget: 1500,
      included: false,
      status: "reportee",
      origin: "pgp",
      level: 2,
    },
  ],
};

export const SEED_RPS: RpsSituation[] = [
  {
    id: "rps-charge",
    title: "Répartition de charge — ligne / pauses",
    unit: "Atelier 3 — équipe de jour",
    facts:
      "Sur une ligne, le poste reste tenu pendant les pauses et les passages en cafétéria. La charge se concentre sur qui reste. Peu de feedback collectif sur le travail livré. Signes de surcharge (heures, tensions d'équipe) sans qu'un relais de fonction soit organisé.",
    scores: { charge: 3, relais: 3, roles: 1, reconnaissance: 2, climat: 1, moyens: 1 },
    attention: "urgence",
    diagnosis:
      "Déséquilibre de charge : le poste n'est pas absorbé quand une partie du collectif n'est pas au poste (pauses, cafétéria, absences). Ce n'est pas un jugement sur des personnes — c'est un défaut d'organisation du relais. Le travail livré n'est pas rendu visible. Le risque n'est pas le « mérite » d'une personne, c'est l'absence d'un rituel collectif de reconnaissance. Si une personne souffre : l'orienter vers la personne de confiance ou le conseiller en prévention aspects psychosociaux — hors de cet outil, sous secret professionnel.",
    measures: [
      "Formaliser un planning de pauses avec relais de fonction : le poste n'est jamais découvert (titulaire de relais = rôle, pas un nom à surveiller).",
      "Objectiver la charge par poste et par shift (unités, dossiers, appels) — jamais par travailleur nommé.",
      "Point d'équipe court (hebdo) : priorités du shift + ce qui a été livré. Compte-rendu anonyme au CPPT si besoin.",
    ],
    avoid: [
      "Nommer, ficher ou photographier des travailleurs.",
      "Contrôler les pauses ou la cafétéria de personnes identifiées.",
      "Transformer le SIPP en outil disciplinaire ou de surveillance.",
      "Traiter une souffrance individuelle dans cet outil — personne de confiance / CP aspects psychosociaux, sous secret.",
    ],
    visitId: "visit-vdb",
    status: "ouverte",
    createdAt: stamp,
    workspaceId: DEMO_WORKSPACE_ID,
    charterAccepted: true,
    demo: true,
  },
];

