/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClasseursPartagesRouteImport } from './routes/classeurs-partages'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConflitsRouteImport } from './routes/conflits'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as FdsRouteImport } from './routes/fds'
import { Route as GroupeRouteImport } from './routes/groupe'
import { Route as PaaRouteImport } from './routes/paa'
import { Route as PartagesRouteImport } from './routes/partages'
import { Route as PgpRouteImport } from './routes/pgp'
import { Route as RappelsRouteImport } from './routes/rappels'
import { Route as RpsRouteImport } from './routes/rps'
import { Route as SignalementRouteImport } from './routes/signalement'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TableauRouteImport } from './routes/tableau'
import { Route as TerrainRouteImport } from './routes/terrain'
import { Route as AnomalieIdRouteImport } from './routes/anomalie.$id'
import { Route as ClasseurIdRouteImport } from './routes/classeur.$id'
import { Route as FdsIndexRouteImport } from './routes/fds.index'
import { Route as FdsIdRouteImport } from './routes/fds.$id'
import { Route as RapportIdRouteImport } from './routes/rapport.$id'
import { Route as RpsIndexRouteImport } from './routes/rps.index'
import { Route as RpsIdRouteImport } from './routes/rps.$id'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as VisiteIdRouteImport } from './routes/visite.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasseursPartagesRoute = ClasseursPartagesRouteImport.update({
  id: '/classeurs-partages',
  path: '/classeurs-partages',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflitsRoute = ConflitsRouteImport.update({
  id: '/conflits',
  path: '/conflits',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const FdsRoute = FdsRouteImport.update({
  id: '/fds',
  path: '/fds',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupeRoute = GroupeRouteImport.update({
  id: '/groupe',
  path: '/groupe',
  getParentRoute: () => rootRouteImport,
} as any)
const PaaRoute = PaaRouteImport.update({
  id: '/paa',
  path: '/paa',
  getParentRoute: () => rootRouteImport,
} as any)
const PartagesRoute = PartagesRouteImport.update({
  id: '/partages',
  path: '/partages',
  getParentRoute: () => rootRouteImport,
} as any)
const PgpRoute = PgpRouteImport.update({
  id: '/pgp',
  path: '/pgp',
  getParentRoute: () => rootRouteImport,
} as any)
const RappelsRoute = RappelsRouteImport.update({
  id: '/rappels',
  path: '/rappels',
  getParentRoute: () => rootRouteImport,
} as any)
const RpsRoute = RpsRouteImport.update({
  id: '/rps',
  path: '/rps',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalementRoute = SignalementRouteImport.update({
  id: '/signalement',
  path: '/signalement',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauRoute = TableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => rootRouteImport,
} as any)
const TerrainRoute = TerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalieIdRoute = AnomalieIdRouteImport.update({
  id: '/anomalie/$id',
  path: '/anomalie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasseurIdRoute = ClasseurIdRouteImport.update({
  id: '/classeur/$id',
  path: '/classeur/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FdsIndexRoute = FdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FdsRoute,
} as any)
const FdsIdRoute = FdsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FdsRoute,
} as any)
const RapportIdRoute = RapportIdRouteImport.update({
  id: '/rapport/$id',
  path: '/rapport/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RpsIndexRoute = RpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RpsRoute,
} as any)
const RpsIdRoute = RpsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RpsRoute,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const VisiteIdRoute = VisiteIdRouteImport.update({
  id: '/visite/$id',
  path: '/visite/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classeurs-partages': typeof ClasseursPartagesRoute
  '/compte': typeof CompteRoute
  '/conflits': typeof ConflitsRoute
  '/connexion': typeof ConnexionRoute
  '/fds': typeof FdsRouteWithChildren
  '/groupe': typeof GroupeRoute
  '/paa': typeof PaaRoute
  '/partages': typeof PartagesRoute
  '/pgp': typeof PgpRoute
  '/rappels': typeof RappelsRoute
  '/rps': typeof RpsRouteWithChildren
  '/signalement': typeof SignalementRoute
  '/support': typeof SupportRouteWithChildren
  '/tableau': typeof TableauRoute
  '/terrain': typeof TerrainRoute
  '/anomalie/$id': typeof AnomalieIdRoute
  '/classeur/$id': typeof ClasseurIdRoute
  '/fds/$id': typeof FdsIdRoute
  '/rapport/$id': typeof RapportIdRoute
  '/rps/$id': typeof RpsIdRoute
  '/visite/$id': typeof VisiteIdRoute
  '/fds/': typeof FdsIndexRoute
  '/rps/': typeof RpsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classeurs-partages': typeof ClasseursPartagesRoute
  '/compte': typeof CompteRoute
  '/conflits': typeof ConflitsRoute
  '/connexion': typeof ConnexionRoute
  '/groupe': typeof GroupeRoute
  '/paa': typeof PaaRoute
  '/partages': typeof PartagesRoute
  '/pgp': typeof PgpRoute
  '/rappels': typeof RappelsRoute
  '/signalement': typeof SignalementRoute
  '/tableau': typeof TableauRoute
  '/terrain': typeof TerrainRoute
  '/anomalie/$id': typeof AnomalieIdRoute
  '/classeur/$id': typeof ClasseurIdRoute
  '/fds/$id': typeof FdsIdRoute
  '/rapport/$id': typeof RapportIdRoute
  '/rps/$id': typeof RpsIdRoute
  '/visite/$id': typeof VisiteIdRoute
  '/fds': typeof FdsIndexRoute
  '/rps': typeof RpsIndexRoute
  '/support': typeof SupportIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classeurs-partages': typeof ClasseursPartagesRoute
  '/compte': typeof CompteRoute
  '/conflits': typeof ConflitsRoute
  '/connexion': typeof ConnexionRoute
  '/fds': typeof FdsRouteWithChildren
  '/groupe': typeof GroupeRoute
  '/paa': typeof PaaRoute
  '/partages': typeof PartagesRoute
  '/pgp': typeof PgpRoute
  '/rappels': typeof RappelsRoute
  '/rps': typeof RpsRouteWithChildren
  '/signalement': typeof SignalementRoute
  '/support': typeof SupportRouteWithChildren
  '/tableau': typeof TableauRoute
  '/terrain': typeof TerrainRoute
  '/anomalie/$id': typeof AnomalieIdRoute
  '/classeur/$id': typeof ClasseurIdRoute
  '/fds/$id': typeof FdsIdRoute
  '/rapport/$id': typeof RapportIdRoute
  '/rps/$id': typeof RpsIdRoute
  '/visite/$id': typeof VisiteIdRoute
  '/fds/': typeof FdsIndexRoute
  '/rps/': typeof RpsIndexRoute
  '/support/': typeof SupportIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classeurs-partages'
    | '/compte'
    | '/conflits'
    | '/connexion'
    | '/fds'
    | '/groupe'
    | '/paa'
    | '/partages'
    | '/pgp'
    | '/rappels'
    | '/rps'
    | '/signalement'
    | '/support'
    | '/tableau'
    | '/terrain'
    | '/anomalie/$id'
    | '/classeur/$id'
    | '/fds/$id'
    | '/rapport/$id'
    | '/rps/$id'
    | '/visite/$id'
    | '/fds/'
    | '/rps/'
    | '/support/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classeurs-partages'
    | '/compte'
    | '/conflits'
    | '/connexion'
    | '/groupe'
    | '/paa'
    | '/partages'
    | '/pgp'
    | '/rappels'
    | '/signalement'
    | '/tableau'
    | '/terrain'
    | '/anomalie/$id'
    | '/classeur/$id'
    | '/fds/$id'
    | '/rapport/$id'
    | '/rps/$id'
    | '/visite/$id'
    | '/fds'
    | '/rps'
    | '/support'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/classeurs-partages'
    | '/compte'
    | '/conflits'
    | '/connexion'
    | '/fds'
    | '/groupe'
    | '/paa'
    | '/partages'
    | '/pgp'
    | '/rappels'
    | '/rps'
    | '/signalement'
    | '/support'
    | '/tableau'
    | '/terrain'
    | '/anomalie/$id'
    | '/classeur/$id'
    | '/fds/$id'
    | '/rapport/$id'
    | '/rps/$id'
    | '/visite/$id'
    | '/fds/'
    | '/rps/'
    | '/support/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClasseursPartagesRoute: typeof ClasseursPartagesRoute
  CompteRoute: typeof CompteRoute
  ConflitsRoute: typeof ConflitsRoute
  ConnexionRoute: typeof ConnexionRoute
  FdsRoute: typeof FdsRouteWithChildren
  GroupeRoute: typeof GroupeRoute
  PaaRoute: typeof PaaRoute
  PartagesRoute: typeof PartagesRoute
  PgpRoute: typeof PgpRoute
  RappelsRoute: typeof RappelsRoute
  RpsRoute: typeof RpsRouteWithChildren
  SignalementRoute: typeof SignalementRoute
  SupportRoute: typeof SupportRouteWithChildren
  TableauRoute: typeof TableauRoute
  TerrainRoute: typeof TerrainRoute
  AnomalieIdRoute: typeof AnomalieIdRoute
  ClasseurIdRoute: typeof ClasseurIdRoute
  RapportIdRoute: typeof RapportIdRoute
  VisiteIdRoute: typeof VisiteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classeurs-partages': {
      id: '/classeurs-partages'
      path: '/classeurs-partages'
      fullPath: '/classeurs-partages'
      preLoaderRoute: typeof ClasseursPartagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflits': {
      id: '/conflits'
      path: '/conflits'
      fullPath: '/conflits'
      preLoaderRoute: typeof ConflitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fds': {
      id: '/fds'
      path: '/fds'
      fullPath: '/fds'
      preLoaderRoute: typeof FdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupe': {
      id: '/groupe'
      path: '/groupe'
      fullPath: '/groupe'
      preLoaderRoute: typeof GroupeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paa': {
      id: '/paa'
      path: '/paa'
      fullPath: '/paa'
      preLoaderRoute: typeof PaaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partages': {
      id: '/partages'
      path: '/partages'
      fullPath: '/partages'
      preLoaderRoute: typeof PartagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pgp': {
      id: '/pgp'
      path: '/pgp'
      fullPath: '/pgp'
      preLoaderRoute: typeof PgpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rappels': {
      id: '/rappels'
      path: '/rappels'
      fullPath: '/rappels'
      preLoaderRoute: typeof RappelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rps': {
      id: '/rps'
      path: '/rps'
      fullPath: '/rps'
      preLoaderRoute: typeof RpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signalement': {
      id: '/signalement'
      path: '/signalement'
      fullPath: '/signalement'
      preLoaderRoute: typeof SignalementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau': {
      id: '/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof TableauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terrain': {
      id: '/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof TerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalie/$id': {
      id: '/anomalie/$id'
      path: '/anomalie/$id'
      fullPath: '/anomalie/$id'
      preLoaderRoute: typeof AnomalieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classeur/$id': {
      id: '/classeur/$id'
      path: '/classeur/$id'
      fullPath: '/classeur/$id'
      preLoaderRoute: typeof ClasseurIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fds/': {
      id: '/fds/'
      path: '/'
      fullPath: '/fds/'
      preLoaderRoute: typeof FdsIndexRouteImport
      parentRoute: typeof FdsRoute
    }
    '/fds/$id': {
      id: '/fds/$id'
      path: '/$id'
      fullPath: '/fds/$id'
      preLoaderRoute: typeof FdsIdRouteImport
      parentRoute: typeof FdsRoute
    }
    '/rapport/$id': {
      id: '/rapport/$id'
      path: '/rapport/$id'
      fullPath: '/rapport/$id'
      preLoaderRoute: typeof RapportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rps/': {
      id: '/rps/'
      path: '/'
      fullPath: '/rps/'
      preLoaderRoute: typeof RpsIndexRouteImport
      parentRoute: typeof RpsRoute
    }
    '/rps/$id': {
      id: '/rps/$id'
      path: '/$id'
      fullPath: '/rps/$id'
      preLoaderRoute: typeof RpsIdRouteImport
      parentRoute: typeof RpsRoute
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/visite/$id': {
      id: '/visite/$id'
      path: '/visite/$id'
      fullPath: '/visite/$id'
      preLoaderRoute: typeof VisiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FdsRouteChildren {
  FdsIdRoute: typeof FdsIdRoute
  FdsIndexRoute: typeof FdsIndexRoute
}

const FdsRouteChildren: FdsRouteChildren = {
  FdsIdRoute: FdsIdRoute,
  FdsIndexRoute: FdsIndexRoute,
}

const FdsRouteWithChildren = FdsRoute._addFileChildren(FdsRouteChildren)

interface RpsRouteChildren {
  RpsIdRoute: typeof RpsIdRoute
  RpsIndexRoute: typeof RpsIndexRoute
}

const RpsRouteChildren: RpsRouteChildren = {
  RpsIdRoute: RpsIdRoute,
  RpsIndexRoute: RpsIndexRoute,
}

const RpsRouteWithChildren = RpsRoute._addFileChildren(RpsRouteChildren)

interface SupportRouteChildren {
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClasseursPartagesRoute: ClasseursPartagesRoute,
  CompteRoute: CompteRoute,
  ConflitsRoute: ConflitsRoute,
  ConnexionRoute: ConnexionRoute,
  FdsRoute: FdsRouteWithChildren,
  GroupeRoute: GroupeRoute,
  PaaRoute: PaaRoute,
  PartagesRoute: PartagesRoute,
  PgpRoute: PgpRoute,
  RappelsRoute: RappelsRoute,
  RpsRoute: RpsRouteWithChildren,
  SignalementRoute: SignalementRoute,
  SupportRoute: SupportRouteWithChildren,
  TableauRoute: TableauRoute,
  TerrainRoute: TerrainRoute,
  AnomalieIdRoute: AnomalieIdRoute,
  ClasseurIdRoute: ClasseurIdRoute,
  RapportIdRoute: RapportIdRoute,
  VisiteIdRoute: VisiteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
